infra:
  - changed-files:
      - any-glob-to-any-file: [
        '!.github/workflows/**',
        '.github/**',
        '.editorconfig',
        '.env*',
        'Makefile',
        'babel.config.js',
        'eslint*.js',
        'jest.config.js',
        'release.config.js',
        'vite.config.js',
        'tsconfig*.json',
      ]

dependencies:
  - changed-files:
      - any-glob-to-any-file: [
        'bun.lock',
        'package-lock.json',
        'yarn.lock',
      ]

ci-cd:
  - changed-files:
      - any-glob-to-any-file: [
        '.github/workflows/**',
        'Dockerfile',
        'Jenkinsfile',
      ]

demo:
  - changed-files:
      - any-glob-to-any-file: [
        'demo/**'
      ]

demo-assets:
  - changed-files:
      - any-glob-to-any-file: [
        'demo/public/**'
      ]

demo-styles:
  - changed-files:
      - any-glob-to-any-file: [
        'demo/styles/**',
      ]

demo-scripts:
  - changed-files:
      - any-glob-to-any-file: [
        'demo/scripts/**',
      ]

styles:
  - changed-files:
      - any-glob-to-any-file: [
        '**/*.scss',
        '**/*.css',
      ]

library:
  - changed-files:
      - any-glob-to-any-file: [
        'packages/**',
      ]

scrollspy-helper:
  - changed-files:
      - any-glob-to-any-file: [
        'packages/.helper/**'
      ]

scrollspy:
  - changed-files:
      - any-glob-to-any-file: [ 'packages/scrollspy/**' ]

tests-library:
  - changed-files:
      - any-glob-to-any-file: [
        'tests/**',
        'test/**',
        '**/spec/**',
        '**/*.test.*',
        '**/*.test-d.*',
        '**/*.spec.*',
      ]

documentation:
  - changed-files:
      - any-glob-to-any-file: [
        'docs/**',
        'AGENTS.md',
        'CHANGELOG.md',
        'CONTRIBUTING.md',
        'LICENSE',
        'README.md',
      ]
