infra:
  - fsegurai

dependencies:
  - fsegurai

ci-cd:
  - fsegurai

demo:
  - fsegurai

demo-assets:
  - fsegurai

demo-styles:
  - fsegurai

demo-scripts:
  - fsegurai

styles:
  - fsegurai

library:
  - fsegurai

scrollspy-helper:
  - fsegurai

scrollspy:
  - fsegurai

tests-library:
  - fsegurai

documentation:
  - fsegurai

default:
  - '@developers'
