blank_issues_enabled: false
contact_links:
  - name: @fsegurai/marked-extensions Issues
    url: https://github.com/fsegurai/marked-extensions/issues
    about: This is for development, support and technical issues/questions.
